# Site settings 配置站点
title: '郑之杰的个人网站'
description: '为天地立心, 为生民立命, 为往圣继绝学, 为万世开太平'
keyword: '数学, 机器学习, 深度学习'
url: '' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# 在服务器上建站时，如果你不需要子域名，请将这一格留空
# if you're using GitHub Pages, set baseurl to your blog's .
# 如果你在使用 GitHub Pages, 请将 baseurl 设置为你的网址的子域名
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# 例如，当你的域名是 "kaeyleo.github.io"  时，这个 url 需要留空
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# 但是，如果你创建了一个叫 "myblog" 的网站，此时网址会变成 "kaeyleo.github.io/myblog" ，这时再将 baseurl 设置为 '/myblog'
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'
  archives: '/archives.html'

# Footer
footer:
  since: 2020

# Author 配置博主信息
author: '郑之杰'
nickname: '杰之'
bio: '热爱旅行家，深度学习者'
#avatar: 'https://github.com/0809zheng/0809zheng.github.io/blob/master/assets/icons/icon.jpg?raw=true'
avatar: 'https://pic.imgdb.cn/item/6184e14b2ab3f51d912026fc.jpg'

# Search 关键词搜索
search: true

# Night mode
nightMode: true

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'
  
  gitalk: true
  gitalk_clientID: 'd45b6dcdac0458c21c03'
  gitalk_Secret: '875ea1d909ddd834f6e6dc7448d0616eec1096a2'
  gitalk_repo: '0809zheng.github.io'
  gitalk_owner: '0809zheng'
  gitalk_admin: '0809zheng'
  distractionFreeMode: true

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/0809zheng'
  weibo: '//weibo.com/u/5627414506'
  zhihu: '//zhihu.com/people/zheng-zhi-jie-36'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
